spring:
   admin:
       client: 
        url: http://localhost:1111/

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: teju2304
    url: jdbc:mysql://localhost:3306/MobileDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url: 
     defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost
